# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21910cbd722fe157057d0cddca7d16a3fd278d5a189d58c35cb400f54bc85eaf43ed6c00fa82481262e99878e41b2f1723ca78e2c9198983e618ca0d89cc8e97

test:
  secret_key_base: 1cae82f74d0f814c8ca7744f787259389fbc8f857a35d9330a4c7eb00ada7dd9ff5e1e82d1288733ea16f1499f153de0f889852f40f82463391bdcb23e9be159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
